short_word_list = ['angel', 'earth', 'empty', 'level', 'light', 'thank', 'theme']

long_word_list = ['actor', 'acute', 'adapt', 'align', 'alike', 'among', 'angel', 'anger', 'angle', 'angry',
                  'beach', 'beams', 'beans', 'beard', 'beast',
                  'class', 'clean', 'clear', 'climb', 'clock', 'close', 'corgi'
                  'dirty', 'ditto', 'doubt', 'draft', 'drama', 'dream',
                  'early', 'earth', 'empty', 'enemy', 'enjoy', 'enter', 'extra', 
                  'faint', 'faith', 'false', 'fatly', 'fault', 'funny', 'furth', 
                  'gaily', 'gayly', 'giant', 'glass', 'gross', 'group', 
                  'house', 'human', 
                  'ideal', 'image', 'iron', 'issue', 
                  'japan', 'joint',
                  'knife', 'known', 
                  'level', 'light',
                  'naval', 'neath', 'never', 'newly', 'night', 'nobly',
                  'offer', 'often', 'order', 
                  'piece', 'pilot', 'pitch', 'prove',
                  'queen', 'queer', 'quick', 'quiet', 'quite',
                  'royal', 'rugby', 'rural', 
                  'style', 'sugar', 'super',
                  'terry', 'thank', 'theme', 
                  'under', 'union', 'unity',
                  'valid', 'value', 'video', 'visit', 'vital',
                  'while', 'white', 'whole', 'woman', 'world', 'worry',
                  'young', 'yummy']
